Initial translation for Serbian language
netceteragroup/pulse-eco-i18n pull request #1
Opened 2021-09-25 20:34 UTC by dusanstojkovic

Mobile translation - initial state - full translation
Web translation - initial state - partial translation (WIP)

2021-10-12 08:27 UTC, sardzoski requested changes

2021-10-12 08:27 UTC, filipsardjoski commented on mobile/translations.trm
> +    <value lang="sr" status="initial">pon</value>
Please use capital first letters for the weekdays

2021-10-12 08:27 UTC, filipsardjoski commented on mobile/translations.trm
> +  <text key="disclaimer_message">
This looks like it's a duplicate of the one on line 236

2021-10-12 08:27 UTC, filipsardjoski commented on mobile/translations.trm
> +    <value lang="de" status="initial">English</value>
This is an extra line

2021-10-20 22:42 UTC, dusanstojkovic commented on mobile/translations.trm
> +    <value lang="sr" status="initial">pon</value>
In Serbian language, names of the days are lower case

2021-10-20 22:43 UTC, dusanstojkovic commented on mobile/translations.trm
> +  <text key="disclaimer_message">
should be fixed now

2021-10-20 22:43 UTC, dusanstojkovic commented on mobile/translations.trm
> +    <value lang="de" status="initial">English</value>
should be removed

2021-10-20 22:48 UTC, dusanstojkovic commented
@sardzoski It should be ok now. 

I intentionally put status="initial" for the translations. Once confirmed how it looks in live app, I plan to change it to translated. I hope this status does not prevent displaying language in UI?

2021-12-14 10:31 UTC, merged